server:
  port: 80

logging:
  level:
    root: info
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.155.20.75:3306/sign?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: E7h!pP2@kTm
mybatis:
  mapper-locations: classpath:mapper/*.xml